---
# Basic demo of using Ansible to create a virtual machine on Pouta.csc.fi
#
# You'll need to download and source your credentials before this will work:
#  https://research.csc.fi/pouta-credentials
#
- name: Pouta ansible demo
  # The OpenStack modules only work with your local machine.
  hosts: localhost
  # And it doesn't use local facts
  gather_facts: false

  vars:
    pouta_username: "{{ lookup('env','OS_USERNAME') }}"
    pouta_password: "{{ lookup('env','OS_PASSWORD') }}"
    tenant_name: "{{ lookup('env','OS_TENANT_NAME') }}"
    auth_url: "{{ lookup('env','OS_AUTH_URL') }}"

    pouta_tiny: 1a0f1143-47b5-4e8a-abda-eba52ae3c5b9
    pouta_centos7: e191e959-2357-41ed-8c11-09438f5b148e

    # These will need changing.
    demo_key: jenkins
    demo_security_groups: default,CSCNets-core
    demo_floating_ip: 86.50.169.188
    demo_network: 16ed69b0-9886-473c-a1c0-a25d80b82d5a

  tasks:
    - name: Create a virtual machine
      os_server:
        state: present
        name: pouta-demo
        auth:
          auth_url: "{{ auth_url }}"
          username: "{{ pouta_username }}"
          password: "{{ pouta_password }}"
          project_name: "{{ tenant_name }}"
        image: "{{ pouta_centos7 }}"
        key_name: "{{ demo_key }}"
        flavor: "{{ pouta_tiny }}"
        security_groups: "{{ demo_security_groups }}"
        nics:
          - net-id: "{{ demo_network }}"
        floating_ips:
          - "{{ demo_floating_ip }}"

