---
# Basic demo of using Ansible to create a virtual machine on Pouta.csc.fi
#
# You'll need to download and source your credentials before this will work:
#  https://research.csc.fi/pouta-credentials
#
- name: Create virtual machine on cPouta
  hosts: localhost # The OpenStack modules run on your local machine.

  vars:
    # These will need changing based on your project
    demo_key: jenkins
    demo_security_groups: default,CSCNets-core,demo-sg
    demo_network: core

  tasks:
    - name: Create security group
      os_security_group: name=demo-sg

    - name: Add rule to security group
      os_security_group_rule:
        security_group: demo-sg
        protocol: tcp
        port_range_min: 80
        port_range_max: 80
        remote_ip_prefix: 0.0.0.0/0

    - name: Create a virtual machine
      register: result
      os_server:
        name: pouta-demo
        image: CentOS-7.0
        flavor: tiny
        key_name: "{{ demo_key }}"
        security_groups: "{{ demo_security_groups }}"
        nics:
          - net-name: "{{ demo_network }}"
    - name: Find the auto-allocated floating IP address
      os_server_facts:
        server: "{{ result.server.id }}"
      until: openstack.networks.values()[0] | length > 1
      delay: 10
    - name: Store the auto-allocated floating IP address
      set_fact: floating_ip={{ openstack.networks.values()[0][1] }}
    - name: Add new host to inventory
      add_host: name={{ floating_ip }} groups=new
    - name: clear ssh known_hosts
      known_hosts: name={{ floating_ip }} state=absent
      when: result | changed
    - name: Wait for instance to be ready
      wait_for: host={{ floating_ip }} port=22 search_regex=OpenSSH delay=10

- name: Configure demo host
  hosts: new
  remote_user: cloud-user
  sudo: yes
  vars:
    demo_photo: kajaani.jpg
    demo_greeting: "Hello from Kajaani!"

  tasks:
   - name: Install a webserver
     yum: name=httpd state=present

   - name: Deploy demo web page
     template: src=templates/demo.html.j2 dest=/var/www/html/index.html owner=apache group=apache mode=0644

   - name: Copy a picture of Kajaani
     copy: src=resources/kajaani.jpg dest=/var/www/html/kajaani.jpg owner=apache group=apache mode=0644

   - name: Install firewalld
     yum: name=firewalld state=present

   - name: Start firewalld
     service: name=firewalld state=started enabled=yes sleep=5

   - name: Configure firewalld for ssh
     firewalld: service=ssh permanent=true state=enabled
     notify:
       - restart firewalld

   - name: Configure firewalld for http
     firewalld: service=http permanent=true state=enabled
     notify:
       - restart firewalld

   - name: Start apache
     service: name=httpd state=started enabled=yes

  handlers:
    - name: restart firewalld
      service: name=firewalld state=restarted sleep=5
     
